def instructions_to_lua(instructions, fileName):

    # Header
    fileContents = "-- This file was generated by the Path Finder program\n\n"

    # Function Definitions
    with open("functions.lua", "r") as f:
        fileContents += f.read()
    fileContents += "\n\n"

    # setup

    # 1. refuel
    fileContents += "refuel()\n"
    # 2. turn around
    fileContents += "turnRight()\n"
    fileContents += "turnRight()\n"
    # 3. pick up items
    fileContents += "collectItems()\n"
    # 4. turn left (to face east), move to start level (current_layer + 2)
    fileContents += "turnLeft()\n"
    fileContents += "up()\n" * 2
    # 5. move forward
    fileContents += "forward()\n"

    # for loop
    for instruction in instructions:
        fileContents += instruction
        fileContents += "\n"

    # write to file
    with open(fileName, "w") as f:
        f.write(fileContents)
    

if __name__ == "__main__":

    instructions = ['forward()', 'turnRight()', 'forward()', 'placeDown()', 'turnLeft()', 'forward()', 'placeDown()', 'forward()', 'placeDown()', 'turnRight()', 'forward()', 'placeDown()', 'turnRight()', 'forward()', 'placeDown()', 'forward()', 'placeDown()', 'forward()', 'turnRight()', 'forward()', 'forward()', 'turnRight()', 'back()', 'down()', 'down()', 'turnLeft()', 'refuel()', 'turnRight()', 'up()', 'up()', 'forward()', 'forward()', 'turnRight()', 'forward()', 'forward()', 'forward()', 'placeDown()', 'turnLeft()', 'forward()', 'placeDown()', 'forward()', 'placeDown()', 'turnRight()', 'turnRight()', 'forward()', 'forward()', 'forward()', 'turnRight()', 'forward()', 'forward()', 'forward()', 'turnRight()']

    instructions_to_lua(instructions)